### POST request - Create new patient
POST http://localhost:4000/patients
Content-type: application/json

{
    "firstName" : "Jake",
    "lastName" : "Bake",
    "email" : "jake.bake@example.com",
    "address" : "123 Main Street",
    "dateOfBirth" : "1995-09-09",
    "registeredDate" : "2025-10-10"
}
###