### PUT request - Update patient
PUT http://localhost:5000/patients/123e4567-e89b-12d3-a456-426614174000
Content-type: application/json

{
    "firstName" : "John",
    "lastName" : "Doe",
    "email" : "john.doe@email.com",
    "address" : "123 Main Street",
    "dateOfBirth" : "1995-09-09"
}
###